### PR TITLE
Update fs-extra to version 10.0.0

### PR DESCRIPTION
**Pull request by jsfix-updater**
This pull request was created using the JSFIX tool (https://jsfix.live) by Coana.tech (https://coana.tech).
The JSFIX run was completed by [mR4smussen](https://github.com/mR4smussen).
It bumps fs-extra to version 10.0.0.

<strong>Sign up your project [here](https://jsfix.live/scanner) to receive notifications about other packages updates JSFIX can help with.</strong>

***

<h3> Pull request details</h3>

<details open><summary><strong> 🚧 - Manual review items (please check before merge)</strong></summary><blockquote class="pr-blockquote"><details>
<summary>Breaking changes not automatically fixable by JSFIX.</summary><blockquote class="pr-blockquote">

<details open>
<summary>General breaking changes (not related to specific API usages in your code).</summary>

* Require Node.js v12+
</details>

</blockquote></details>

</blockquote></details><details><summary>Additional details</summary><blockquote class="pr-blockquote"><details>
<summary>Breaking changes where JSFIX found that there were no occurrences.</summary>

* Allow copying broken symlinks
* Ensure correct type when destination exists for ensureLink*()/ensureSymlink*()
* Error when attempting to copy*() unknown file type
* Remove undocumented options for remove*()
</details>

</blockquote></details>

***

If you would like to provide feedback to the JSFIX developers, then please leave a comment on this pull request.

### CODE REVIEW

**Comment by Apollon77** [comment]
I use dependabot ... and also 10.0.0 is no longer current version

**Comment by mtorp** [comment]
Unlikely, Dependabot, JSFIX checks if your code is affected by breaking changes, and in many cases also automatically transforms your code accordingly.

> and also 10.0.0 is no longer current version

That's a good point. Actually it upgrades to 10.1.0, which is the newest as of this comment, but we should be more clear about that.

**Comment by Apollon77** [comment]
Then in act thank you, would be cool to see such a "and in many cases also automatically transforms your code accordingly." case :-)

**Comment by mtorp** [comment]
Thanks!
Yes. fs-extra is maybe not the most interesting case since all the breaking changes rarely affect code in practice.
As a more interesting example, have a look at https://github.com/energywebfoundation/switchboard-dapp/pull/654.
There are also some other examples on the webpage.

**Pull request closed without merging**
